services:
  database-pg:
    image: postgres:15-alpine
    container_name: database-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: senhadodev
      POSTGRES_DB: checkly_db_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d checkly_db_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  dashboard-database:
    image: adminer
    container_name: dashboard-database
    restart: unless-stopped
    depends_on:
      database-pg:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  postgres-data:
