basePath: /v1
definitions:
  GustavoCesarSantos_checkly-api_internal_modules_monitor_presentation_dtos.HealthCheckResponse:
    properties:
      status:
        example: available
        type: string
      system_info:
        $ref: '#/definitions/GustavoCesarSantos_checkly-api_internal_modules_monitor_presentation_dtos.SystemInfo'
    type: object
  GustavoCesarSantos_checkly-api_internal_modules_monitor_presentation_dtos.SystemInfo:
    properties:
      environment:
        example: development
        type: string
      time:
        example: "2024-06-01T12:00:00Z"
        type: string
    type: object
  GustavoCesarSantos_checkly-api_internal_modules_urls_domain.UrlStatus:
    enum:
    - 10
    - 20
    - 25
    - 30
    type: integer
    x-enum-varnames:
    - StatusHealthy
    - StatusDegraded
    - StatusRecovering
    - StatusDown
  GustavoCesarSantos_checkly-api_internal_modules_urls_presentation_dtos.CreateUrlRequest:
    properties:
      address:
        example: https://api.meuservico.com/health
        type: string
      contact_email:
        example: meu_contato@email.com
        type: string
      interval_minutes:
        example: 5
        type: integer
      next_check:
        type: string
      retry_limit:
        example: 3
        type: integer
      status:
        $ref: '#/definitions/GustavoCesarSantos_checkly-api_internal_modules_urls_domain.UrlStatus'
    type: object
  GustavoCesarSantos_checkly-api_internal_modules_urls_presentation_dtos.CreateUrlResponse:
    properties:
      id:
        example: "1"
        type: string
    type: object
  GustavoCesarSantos_checkly-api_internal_shared_utils.ErrorEnvelope:
    properties:
      error:
        example: error message
        type: string
    type: object
  internal_modules_monitor_presentation_handlers.HealthCheckEnvelope:
    properties:
      health_check:
        $ref: '#/definitions/GustavoCesarSantos_checkly-api_internal_modules_monitor_presentation_dtos.HealthCheckResponse'
    type: object
  internal_modules_urls_presentation_handlers.CreateUrlEnvelop:
    properties:
      url:
        $ref: '#/definitions/GustavoCesarSantos_checkly-api_internal_modules_urls_presentation_dtos.CreateUrlResponse'
    type: object
info:
  contact:
    email: gustavocs789@gmail.com
    name: Gustavo Cesar Santos
  description: API respons√°vel por monitorar URLs e avaliar sua disponibilidade.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Checkly API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Monitor API health.
      produces:
      - application/json
      responses:
        "200":
          description: API is healthy
          schema:
            $ref: '#/definitions/internal_modules_monitor_presentation_handlers.HealthCheckEnvelope'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/GustavoCesarSantos_checkly-api_internal_shared_utils.ErrorEnvelope'
      summary: Monitor health check
      tags:
      - Monitor
  /urls:
    post:
      consumes:
      - application/json
      description: Create a new url for monitoring.
      parameters:
      - description: Create Url request
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/GustavoCesarSantos_checkly-api_internal_modules_urls_presentation_dtos.CreateUrlRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Board successfully created
          schema:
            $ref: '#/definitions/internal_modules_urls_presentation_handlers.CreateUrlEnvelop'
        "400":
          description: Empty body request
          schema:
            $ref: '#/definitions/GustavoCesarSantos_checkly-api_internal_shared_utils.ErrorEnvelope'
        "402":
          description: Invalid request (e.g., missing parameters or validation error)
          schema:
            $ref: '#/definitions/GustavoCesarSantos_checkly-api_internal_shared_utils.ErrorEnvelope'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/GustavoCesarSantos_checkly-api_internal_shared_utils.ErrorEnvelope'
      summary: Create a new url
      tags:
      - Url
swagger: "2.0"
